name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build latest
      run: docker build ./tags/latest --tag renfis/h2database:latest
    - name: Build 1.4.200
      run: docker build ./tags/1.4.200 --tag renfis/h2database:1.4.200
  
